version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    command: npm start
  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME:basheer
      - MONGO_INITDB_ROOT_PASSWORD:mongopass
