version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
    command: npm start
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=basheer
      - MONGO_INITDB_ROOT_PASSWORD=mongopass
    volumes:
      - mongo-database:/data/db
volumes:
  mongo-database: 
